name: Package - All

on:
  workflow_dispatch:

jobs:
  linux:
    uses: DMJC/dxx-vr/.github/workflows/package-linux.yml@vr-support-working
  windows:
    uses: DMJC/dxx-vr/.github/workflows/package-windows.yml@vr-support-working
  msvc:
    uses: DMJC/dxx-vr/.github/workflows/package-msvc.yml@vr-support-working
  macos:
    uses: DMJC/dxx-vr/.github/workflows/package-macos.yml@vr-support-working
  macos-arm:
    uses: DMJC/dxx-vr/.github/workflows/package-macos-arm.yml@vr-support-working
